name: Continuous Integration
on:
  push:
jobs:
  build:
    name: HHVM ${{matrix.hhvm}} - ${{matrix.os}}
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os: [ macos ]
        hhvm:
          - 'nightly'
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install HHVM (brew)
        if: matrix.os == 'macos'
        run: |
          brew tap hhvm/hhvm
          
          # trigger the CI
          brew update
          
          if [ "${{matrix.hhvm}}" = "latest" ]; then
            brew install hhvm
          else
            HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=true brew install hhvm-${{matrix.hhvm}}
          fi
      - name: Inspect HHVM and Hack versions
        run: |
          ls -l /usr/local/Cellar/hhvm-nightly
          ls -l /usr/local/Cellar/hhvm-nightly/2022.03.09
          ls -l /usr/local/Cellar/hhvm-nightly/2022.03.09/bin
          otool -L /usr/local/Cellar/hhvm-nightly/2022.03.09/bin/hhvm
          ls -l /usr/local/opt/boost/lib/
          otool -L /usr/local/opt/boost/lib/libboost_filesystem-mt.dylib
          hhvm --version
          hh_client --version
